# -*- coding: utf-8 -*-
"""Capstone Project Graphical Analysis Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FvN9zJ74n0aj_Yjl4tfnto6awjdeJNnB
"""



"""# ***Graphical Analysis of Car_Details dataset.***

In this I am going to use updated dataset of Car Details which I have already updated in Data Cleaning , Data Preprocessing File.

In terms of Updation, I have done the following:

Handling duplicated and missing Values.

Removing Outliers.

Feture Engineering where I have extracted brand names of the car from their names.
"""

# Commented out IPython magic to ensure Python compatibility.
# Importing Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
sns.set_style('darkgrid')

import warnings
warnings.filterwarnings('ignore')

# Loading Dataset
car_ga = pd.read_csv('/content/car_updated.csv')
car_ga

# showing first 5 rows
car_ga.head()

# showing last 5 rows
car_ga.tail()

# showing Dimensions of Dataset
car_ga.shape

"""**Observation :**

This shows we have 3388 rows and 10 columns in the dataset
"""

# checking for columns
car_ga.columns

"""As we can see there is one unnecessary column in the dataset i.e.. 'Unnamed: 0'. which is nothing but just a index number of the values. So, we will drop this column from the dataset"""

# Dropping 'Unnamed: 0' column
car_ga = car_ga.drop('Unnamed: 0', axis=1)
car_ga

# checking for data types
car_ga.dtypes

# checking for duplicated values
car_ga.duplicated().sum()

# no duplicate values found

# checking for null values
car_ga.isnull().sum()

# no null values found

# showing information about dataset
car_ga.info()

# showing Statistical Analysis of the Dataset.
car_ga.describe(include='all')

"""# ***Unique Values of Features***"""

# Showing Unique values of year column
car_ga['year'].unique()

# showing Unique values of selling_price column
car_ga['selling_price'].unique()

# showing unique values of km_driven column
car_ga['km_driven'].unique()

# showing unique values of categorical columns
cat_cols = [col for col in car_ga.columns if car_ga[col].dtype == 'object']

for col in cat_cols:
  print(car_ga[col].unique())

"""# ***Data Visualization***

***Histplot for Data***
"""

# Showing Histplot
car_ga.hist(figsize=(10,10),color='MidnightBlue')
plt.show()

"""# ***Feature Wise Visualization***

# ***1. Brand Column***

***Total No. of cars sold by different brands.***
"""

plt.figure(figsize=(10,6))
counts = car_ga["brand"].value_counts().sort_values(ascending=False)
ax = sns.barplot(x=counts.index, y=counts.values,palette="Set3")
ax.bar_label(ax.containers[0], )
plt.xlabel("Car Brands")
plt.ylabel("Total No. of cars sold")
plt.title("Total Cars Sold by Different Brands",fontweight="black", fontsize=15)
plt.xticks(rotation=90)
plt.show()

"""***Insights :***

We can see that Maruti has sold the highest number of cars.

Maruti is the highest preferred brand.

Brands like OpelCorsa, Daewoo and Force are the least preferred brands.

The Top 5 Brands who sold the most number of cars are -

 Maruti

 Hyundai

 Mahindra

 Tata

 Ford

# ***Market share of Top 10 Car Brands***
"""

plt.figure(figsize=(12,10))
top_brands = car_ga["brand"].value_counts().sort_values(ascending=False).head(10)
plt.pie(top_brands, labels=top_brands.index, autopct='%1.1f%%')
plt.title("Market Share of Top 10 Brands")
plt.xlabel("Brands")
plt.show()

"""***Insights :***

Maruti has the highest market share which is about 33.5% of the total.

Out of these Top 10 brands, Volkswagen has the lowest market share which is about 2.9% of the total.

# ***Average Selling Price of each Car Brand***
"""

avg_car_price = car_ga.groupby(['brand'])[['selling_price']].mean()
avg_car_price.sort_values(by='selling_price', ascending=True, inplace=True)
ax   = avg_car_price.plot(kind='barh', color='teal' , figsize=(10,16) ,title= 'Avarege Selling Price of Each Car Brand')
ax.bar_label(ax.containers[0], )
plt.show()

"""***Insights :***

We can clearly see Audi is one of the highest price car brand.

# ***Average km driven of each Car Brand***
"""

avg_km_driven = car_ga.groupby(['brand'])[['km_driven']].mean()
avg_km_driven.sort_values(by='km_driven', ascending=False, inplace=True)
ax   = avg_km_driven.plot(kind='bar', color='#800000' , figsize=(10,16) ,title= 'Avarege km driven of Each Car Brand')
plt.ylabel('km_driven')
plt.show()

"""***Insights:***

From the plot we can see that the Mitsubishi car brand has the highest average km driven.

The Toyota brand also has the high average km driven.

The Datsun car brand has the lowest average km driven.

# ***Distribution of each Car Brand on the basis of transmission.***
"""

plt.figure(figsize=(15,10))
car_count = sns.countplot(x='brand', data=car_ga, palette="Set1",hue='transmission')
# Display labels on the bars
for container in car_count.containers:
    car_count.bar_label(container)
plt.xticks(rotation=90)
plt.show()

"""***Insights :***

In terms of Manual Transmission, Maruti has the most no. of cars.

In terms of Automatic Transmission, Hyundai leads than other car brands

# ***2. Name Column***

***Top 15 cars sold most no. of times.***
"""

most_sold_cars = car_ga['name'].value_counts().head(10).sort_values().plot(kind='barh', figsize=(8,5), color='purple')
most_sold_cars.bar_label(most_sold_cars.containers[0], )
plt.show()

"""***Insights :***

Maruti Swift Dzire VDI sold the most number of times.

The Top 5 cars sold the most number of times are -

 Maruti Swift Dzire VDI

 Maruti Alto 800 LXI

Maruti Alto LXi

Maruti Alto LX

Maruti Swift VDI BSIV

# ***3. Year Column***

***Total of Cars Sold Each Year***
"""

cars_sold_yearly = car_ga['year'].value_counts().sort_values().plot(kind='bar', figsize=(8,5), color='hotpink')
plt.xlabel("Years", labelpad=14)
plt.ylabel("Total No. of cars sold", labelpad=14)
plt.title("Total No. of Cars Sold Each Year")
plt.xticks(rotation=90)
plt.show()

"""***Insights:***

The Highest number of cars sold in 2012
Other than 2012, [2013, 2014, 2016, 2017, 2018] are the other years in which the cars sold in high numbers.

The lowest number of cars sold in 1992

# ***Selling of Car Each Year Transmission Wise***
"""

plt.figure(figsize=(15,7))
sns.histplot(x='year',
              hue='transmission',
              data=car_ga,
              palette='ocean')
plt.xlabel('Season',fontsize=12)
plt.ylabel('Count',fontsize=12)
plt.title('Car sold each year transmission wise', fontsize=15)
plt.show()

"""***Insights :***

In 2012, Manual Transmission cars sold the most.

We can see the years between 2011 and 2018 are the most sold years for manual transmission cars.

In 2017, Automatic Transmission cars sold the Highest.

The Year 2017, 2018, and 2019 are the most sold years for automatic transmission cars

# ***How does year affects km_driven?***
"""

plt.figure(figsize=(12,10))
plt.title('Yearly km_driven Distribution', fontsize=18)
sns.barplot(data=car_ga, x='year', y='km_driven')
plt.xticks(rotation=90)
plt.show()

"""***Insights:***

From the plot we can see that in year 1997 the most km_driven cars are sold.

In year 2020, the least km_driven cars are sold.

# ***4. Visualizaion of Categorical Features.***
"""

# Defining function to plot graph

def categorical_visualization(cols):
    plt.figure(figsize=(15,10))
    plt.subplot(1,3,1)
    sns.countplot(x=cols,data=car_ga,palette="flag",order=car_ga[cols].value_counts().index)
    plt.title(f"{cols} Distribution",fontweight="black",fontsize=15)
    plt.xticks(rotation=90)

    plt.subplot(1,3,2)
    sns.boxplot(x=cols,y="selling_price",data=car_ga,palette="flag")
    plt.title(f"{cols} vs Price",fontweight="black",fontsize=15)
    plt.xticks(rotation=90)

    plt.subplot(1,3,3)
    x=pd.DataFrame(car_ga.groupby(cols)["selling_price"].mean().sort_values(ascending=False))
    sns.pointplot(x=x.index,y="selling_price",data=x,palette="flag")
    plt.title(f"{cols} vs Average Price",fontweight="black",fontsize=15)
    plt.xticks(rotation=90)
    plt.tight_layout()
    plt.show()

"""***Fuel Column***"""

categorical_visualization('fuel')

"""***Insights :***

From the First Plot, We can clearly see that Cars having Petrol fuel system is mostly sold and having electric cars is least sold.

From the second plot we can make an insight that Petrol Fuel Sysytem cars are availabe within every price range.

Diesel fuel type are having most of the cars price near to average price of the cars. But the Petrol Fuel Type cars are having cars with high prices also.

From the third plot we can make an insight that the Average price of diesel fuel type cars are more than other fuel type cars.

So we can say that customers prefer those cars which consumes less price in fuels.

***Seller_Type Column***
"""

categorical_visualization('seller_type')

"""***Insights :***

From the First Plot, We can clearly see that Individuals seller type sold the most no. of cars.

From the second plot we can make an insight that both the individuals and dealers seller type sold the car in every price range.But, the trustmark dealers mostly deal in high price cars.

Individuals seller type car's average price is very low so, we can conclude this that most of the people prefer individuals seller type cars.

# ***Transmission Column***
"""

categorical_visualization('transmission')

"""***Insights:***

From the First Plot, We can clearly see that Manual Transmission cars sold the most.

From the second plot we can make an insight that Manual type cars are availabe within every price range whereas Automatic type cars are deal with high prices cars.

Manual type cars are having most of the cars price near to average price of the cars.but, the manual type cars having very low average price.

So we can say that customers mostly prefer manual type cars

# ***Owner Column***
"""

categorical_visualization('owner')

"""***Insights :***

From the First Plot, We can clearly see that Cars are mostly sold to the first owners.

From the second plot we can make an insight that second type owner are mostly deal with every price range.

Test drive car owners mostly take high price carsas there average price is even higher than other owners.

So, we can conclude that cars are mostly sold to first and second owners.

# ***5. Km_driven Column***
"""

plt.figure(figsize=(10,5))
sns.lineplot(x = car_ga['year'], y =car_ga['km_driven'],color='#3F000F')
plt.show()

"""***Insight:***

We can clearly see with the year the km_driven of the cars keeps on decreasing.

# ***6. Transmission Column***

***Relationship between Transmission and Selling price on the basis of seller type.***
"""

plt.figure(figsize=(5,5))
g = sns.FacetGrid(car_ga, col="transmission", hue="seller_type", palette="bright",height=5)
g = (g.map(sns.histplot, "selling_price", kde=True).add_legend())
plt.show()

"""***Insights:***

When Transmission is Manual, Individual seller type deal with lower price cars.

When Transmission is Manual, Dealers seller type deal with all price ranges.

When Transmission is manual, Trustmark dealers mostly deal with high price cars.

When Transmission is Automatic, Trustmark dealers mostly deal with high price cars.

When Transmission is Automatic, Individuals seller type deal high prices camparitively manual car types.

When Transmission is Automatic, Dealers seller type deal with high price cars comparatively manual car types.

# ***7. Visualizing Target Feature (selling_price)***
"""

# Showing Car Price Distribution plot
plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
sns.distplot(car_ga["selling_price"],color="red",kde=True)
plt.title("Car Price Distribution",fontweight="black",pad=20,fontsize=15)

# Showing Car Price Spread plot
plt.subplot(1,2,2)
sns.boxplot(y=car_ga["selling_price"],palette="Set2")
plt.title("Car Price Spread",fontweight="black",fontsize=15)
plt.tight_layout()
plt.show()

"""***Insights :***

We can clearly observe that our Car Price Feature is Slightly Rightly Skewed Distribution.

We can clearly observe that there is a significant difference between mean & median value.

# ***Relationship Between Selling Price and Year on the basis of fuel.***
"""

plt.figure(figsize=(10,10))
sns.scatterplot(data=car_ga, x='year', y='selling_price', hue='fuel', style='fuel',palette='RdBu')
plt.title('Relationship Between Selling Price and Year on the basis of fuel')
plt.show()

"""***Insight:***

With the increase in the year the selling price of the diesel cars keeps on increasing, But in 2020 the selling price of cars having petrol fuel type is high.

# ***Relationship Between Selling Price and Year on the basis of transmission.***
"""

plt.figure(figsize=(10,10))
sns.scatterplot(data=car_ga, x='year', y='selling_price', hue='transmission', style='transmission',palette='GnBu')
plt.title('Relationship Between Selling Price and Year on the basis of transmission')
plt.show()

"""***Insight:***

With the increase in the year the selling price of the manual type cars keeps on increasing.

# ***Plotting Correlation Plot***
"""

# Plotting a Heatmap for correlation using correlation table
fig, axes = plt.subplots(figsize=(8,5))
sns.heatmap(car_ga.corr(), ax=axes, annot=True, linewidths=0.1, fmt='.2f', square=True)
plt.show()

"""***Insight:***

from this plot we can see that year are selling price are highly positively correlated

But, year and km_driven are highly negatively correlated

# ***Plotting Pairplot***
"""

sns.pairplot(car_ga,kind='scatter',diag_kind='kde')
plt.show()

"""# ***Conclusion***

Here I have used the updated car dataset which is taken from the car details dataset from kaggle. Before applying Visualization , first i updated the dataset like perform some data cleaning , outliers removal and then i visualized the dataset using different visualization techniques(matplotlib and seaborn). I have used various plots in this like barplot, histplot, scatterplot, boxplot and many more.I also used correlation plot to check the correlation between different features, where I have found that With the increase in the year the selling price keeps on increasing , but the km_driven keeps on decreasing. I have also used pairplot to check the relationship between different features. From the Analysis I came to know that
the Top 5 Brands who sold the most number of cars are-

1. Maruti, Hyundai, Tata, Ford and Mahindra.
2. Audi is one of the highest price car brand.
3. Mitsubishi car brand has the highest average km driven.
4. In the year 1997 the most km_driven cars are sold.
5. The Top 5 cars sold the most number of times are -
Maruti Swift Dzire VDI, Maruti Alto 800 LXI, Maruti Alto LXi, Maruti Alto LX, Maruti Swift VDI BSIV.
6. In 2012, Manual Transmission cars sold the most.
7. In 2017, Automatic Transmission cars sold the Highest.
8. The Highest number of cars sold in 2012 9. Customers mostly prefer manual type cars. 10. Cars are mostly sold to first and second owners
"""